title: Prospectiva de la Tecnología
description: Prácticas sobre inteligencia artificial generativa y modelos de lenguaje
theme: just-the-docs

url: https://sebas30073007.github.io/prospectiva_de_la_tecnologia

aux_links:
  Repositorio: https://github.com/sebas30073007/prospectiva_de_la_tecnologia

# Just the Docs config
search_enabled: true
heading_anchors: true
color_scheme: light

mermaid:
  version: "11"
